version: '3.8'
services:

    frontend:
      build:
        context: ./deep-dream-front-end 
      ports:
        - "5173:5173"
      volumes:
        - ./deep-dream-front-end/src:/app/src
      stdin_open: true
      tty: true
      depends_on:
        - server
      networks:
        - app-network

    server:
      image: nginx:stable-alpine
      ports:
        - "8000:90"
      volumes:
        - ./deep-dream-api:/var/www/html
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - php
        - appdb

    php:
      build:
        context: ./dockerfiles
        dockerfile: php.dockerfile
      volumes:
        - ./deep-dream-api:/var/www/html:delegated

    artisan:
      build:
        context: ./dockerfiles
        dockerfile: php.dockerfile
      volumes:
        - ./deep-dream-api:/var/www/html
      entrypoint: [ "php", "/var/www/html/artisan" ]

    composer:
      build:
        context: ./dockerfiles
        dockerfile: composer.dockerfile
      volumes:
        - ./deep-dream-api:/var/www/html:delegated

    appdb:
      image: mysql:8.3
      restart: unless-stopped
      env_file:
        - ./.env
      environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_USER: ${DB_USERNAME}
      volumes:
        - ./initdb:/docker-entrypoint-initdb.d
        - data:/var/lib/mysql
      ports:
        - 3306:3306
      networks:
        - db

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: unless-stopped
      env_file:
        - ./.env
      environment:
        PMA_HOST: appdb
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      depends_on:
        - appdb
      ports:
        - 8443:80
      networks:
        - db
volumes:
  data:
  logs:

networks:
  app-network:
    driver: bridge
  db: